from flask import Flask,request,jsonify
import subprocess
import pyrebase
import os
#configration files of firebase storage
config ={
  "apiKey": "AIzaSyAPiC14hRZ1nuwk0LxKCNE0pkASeYN-deQ",
  "authDomain": "upload-67274.firebaseapp.com",
  "projectId": "upload-67274",
  "storageBucket": "upload-67274.appspot.com",
  "serviceAccount": "serviceAccountKey.json",
  "databaseURL":"https://upload-67274-default-rtdb.firebaseio.com/"
};
firebase_storage = pyrebase.initialize_app(config)
storage = firebase_storage.storage()
app = Flask(__name__)
@app.route("/", methods=['GET'])
def home():
    filename=str(request.args['query'])
    #Downloading video from firebase from files folder to local directory of project
    storage.download("files/{}".format(filename),"video.mp4")
    #calling model.py
    subprocess.run(["python","model.py"])
    print("video subtitled sucess")
    file_path = "video_Subtitled.mp4"
    remote_path = "files_sub/{}".format(filename)
    storage.child(remote_path).put(file_path)
    #copying the subtitled video
    subprocess.run(["python","shift.py"])
    #removing the files generated by model
    subprocess.run(["python","remove.py"])
    dic={}
    dic['output'] = filename
    return jsonify(dic)  
if __name__ == "__main__":
    app.run()
